#!/usr/bin/env bash

# USE: ./fastmaker inputfile.png 300 outputdir/
# where 300 is square bounds into which the image will fit (but not made to fill)
# i used 1100 for the bison
# https://www.smashingmagazine.com/2015/06/efficient-image-resizing-with-imagemagick/

mogrify -path "$3" -filter Triangle -define filter:support=2 -thumbnail "$2" -unsharp 0.25x0.25+8+0.065 -dither None -posterize 136 -quality 82 -define jpeg:fancy-upsampling=off -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB -strip "$1"
